name: mailgun
description: A Flutter package for sending email using Mailgun API
version: 0.1.3
homepage: https://github.com/dotronglong/flutter-mailgun

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  mail:
    git:
      url: git://github.com/jonas1-4/flutter-mail
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
